import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { useState, useEffect } from 'react';

export default function Home() {
  const llamarApi = async(query) => {
    // try {
      const resp = await fetch (`/api/${query}`);
      // const resp = await fetch (`/api`);
      const respJson = await resp.json();
      console.log(respJson);
    // } catch {
    //   console.log("No wei");
    // }
  }

  const [query, setQuery] = useState("");

  const handleChange = (event) => {
    setQuery(event.target.value);
  };

  const llamadaEjemplo = async () => {
    console.log("Voy a llamar a la API");
    await llamarApi(query);
    console.log("Ya la llamé");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecomedi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Ecomedi!
        </h1>

        <p className={styles.description}>
          ¡Ingresa el nombre de un medicamento y te daremos las opciones más económicas del mercado!
        </p>

        <TextField id="outlined-basic" label="Ejemplo input" variant="outlined" onChange={handleChange}/>
        <Button variant="contained" onClick={llamadaEjemplo}>Buscar</Button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
